version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
      - VITE_ML_SERVICE_URL=http://localhost:8000
#     depends_on:
#       - backend

#   # Rest of the services remain the same...
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./backend:/app
#     environment:
#       - GO_ENV=development
#       - DB_HOST=postgres
#       - DB_PORT=5432
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#     depends_on:
#       - postgres
#       - redis

#   ml-service:
#     build:
#       context: ./ml-service
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./ml-service:/app
#       - ./ml-service/models:/app/models
#     environment:
#       - PYTHONUNBUFFERED=1
#       - MODEL_PATH=/app/models
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]

#   postgres:
#     image: postgres:14-alpine
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=${DB_NAME}

#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

# volumes:
#   postgres_data:
#   redis_data: